"""PMOPort: the Protocol every PMO adapter implements, plus the capability
negotiation DTO (docs/05). Normalized domain DTOs live in domain.model."""

from typing import Protocol

from pydantic import BaseModel

from ..domain.model import Activity, Mission, NormalizedStatus


class PMOCapabilities(BaseModel):
    projects_supported: bool
    project_labels_supported: bool
    attachment_max_bytes: int
    native_label_swap_atomic: bool
    relations_supported: bool = False


class PMOPort(Protocol):
    """docs/05 §1 — M2 implements the read path + labels; writes land M3–M5."""

    async def list_missions(self, team_ref: str) -> list[Mission]: ...
    async def get_mission(self, pmo_id: str) -> Mission: ...
    async def get_activity(self, pmo_id: str) -> Activity: ...
    async def post_comment(self, pmo_id: str, markdown: str) -> None: ...
    async def set_status(self, pmo_id: str, status: NormalizedStatus) -> None: ...
    async def swap_labels(self, pmo_id: str, remove: set[str], add: set[str]) -> None: ...
    async def ensure_labels(self, team_ref: str, names: set[str]) -> None: ...
    async def create_relation(self, blocker_id: str, blocked_id: str) -> None: ...
    async def create_project_update(self, project_id: str, body: str) -> None: ...
    def capabilities(self) -> PMOCapabilities: ...
